### ISSUE TITLE
Domain hosting in Netlify

### ISSUE THREAD

**Issue by SP-INDT-OpenCert** [OpenCerts/demo-opencerts-renderer#192]
hi,

Currently I'm using my presonal domain for testing, but now I'm switching over the domain under SP.
Any way to us SP's subdomain for Netlify, I got an error when I tried to link it.
![image](https://user-images.githubusercontent.com/54525549/69293836-0981ce00-0c45-11ea-8df2-5b122f6634ee.png)

Regards,
Ryan

**Comment by Nebulis** [comment]
Hi, M

aybe this could help => https://docs.netlify.com/domains-https/custom-domains/

You should try to reach netlify community for help on this
