### ISSUE TITLE
Getting error in npm run dev command

### ISSUE THREAD

**Issue by nikhilranosys** [OpenCerts/demo-opencerts-renderer#210]
Hi,

I took clone of this repository and after doing npm install when I run npm run dev it gives me below error:

```
> opencerts-demo-decentralized-renderer@0.0.0-development dev D:\Local Disk\New\Desktop\Projects\smu\opencerts\forked\demo-opencerts-renderer
> NODE_ENV=development webpack-dev-server

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencerts-demo-decentralized-renderer@0.0.0-development dev: `NODE_ENV=development webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencerts-demo-decentralized-renderer@0.0.0-development dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nikhil Gaur\AppData\Roaming\npm-cache\_logs\2019-11-27T09_18_11_161Z-debug.log
```

I am running it on a windows machine.

**Comment by Nebulis** [comment]
Hi,

You will need to use cross-env => https://www.npmjs.com/package/cross-env

1. Install cross-env
```
npm i --save-dev cross-env
```
2. Add cross-env to command lines with environment variables. For instance replace the highlighted line (https://github.com/OpenCerts/demo-opencerts-renderer/blob/master/package.json#L23) by the following:
```
    "dev": "cross-env NODE_ENV=development webpack-dev-server",
```

I may add it later to this repo. Let me know if you face any issue

**Comment by nikhilranosys** [comment]
Thanks @Nebulis for the reply. I did as you shared but now I am getting below error when I run npm run dev:

```
WARNING in EnvironmentPlugin - NET environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.
```

**Comment by Nebulis** [comment]
Just a warning, it should be fine. Note than running this wont render anything, the renderer expect a document to display anything.

- you can use `npm run storybook` to see the different components (it should open a link in your browser)
you can use `npm run storybook:build` to build a version of your documentation that you can host on any static website
- you can use `npm run test` to run tests
- you can use `npm run lint` to run linting
- you can use `npm run build` to build a static version of the application, that can be host on any website

Documentation is not completely up to date, I will try to work on this in the coming days.

May I ask you how you ended up cloning this repository? (it's currently the easiest way to create your own decentralized renderer, so it's a good thing that you did it, I just want to understand by which process you decided to use this one, maybe it's referenced somewhere)

**Comment by Nebulis** [comment]
Hi,

I've updated the documentation on https://github.com/Open-Attestation/decentralized-renderer-react-template which is actually the template we have rebuild this demo on
