### ISSUE TITLE
npm run dev fail 

### ISSUE THREAD

**Issue by laykoonjune** [OpenCerts/demo-opencerts-renderer#368]
![image](https://user-images.githubusercontent.com/46921398/75022266-bd0e8e80-54d0-11ea-81da-4cdec299fddf.png)
Just download the latest code from github and unable to run it. 
Failed at the opencerts-demo-decentralized-renderer@0.0.0-development dev script.

**Comment by Nebulis** [comment]
looks like you are using windows, you will need cross-env => https://www.npmjs.com/package/cross-env
