### ISSUE TITLE
npm run dev failed

### ISSUE THREAD

**Issue by laykoonjune** [OpenCerts/demo-opencerts-renderer#369]
Encounter the below error while running npm run dev

![image](https://user-images.githubusercontent.com/46921398/75332781-f0319300-58bf-11ea-9711-9587cf60658c.png)
![image](https://user-images.githubusercontent.com/46921398/75332840-06d7ea00-58c0-11ea-864f-e8967a183a67.png)

**Comment by Nebulis** [comment]
Hmmm try to reinstall dependencies (remove node modules)

**Comment by laykoonjune** [comment]
Encounter the same error even after reinstalling.

**Comment by Nebulis** [comment]
full log ?

**Comment by laykoonjune** [comment]
[Error log.txt](https://github.com/OpenCerts/demo-opencerts-renderer/files/4259212/Error.log.txt)

**Comment by Nebulis** [comment]
that's the full log ? there is nothing more ?

**Comment by laykoonjune** [comment]
Yes that is the full log nothing more to this.

**Comment by Nebulis** [comment]
I dunno. I googled the error and found this https://github.com/webpack-contrib/css-loader/issues/447. You can try but if this doesn't help I can't help more

**Comment by laykoonjune** [comment]
The code are able to compiled with warning after i change  target: "node" in webpack.config 

Just to check for the updated code it will not launched browser after it has been compiled? As I run the older version of the code it will launcher the browser after compilation.

**Comment by Nebulis** [comment]
I dunno for older version but yes it doesnt open the browser (dont forget that the browser will be blank as explained in readme)

**Comment by laykoonjune** [comment]
Yes, I understand the browser will be blank.  

I realized that in the demo sample Govtech provide other than the .tsx there are also stories.mdx is it necessary that we need to  create these files and how do we view the template we have create locally or we have to deploy to view?

**Comment by Nebulis** [comment]
No stories are just for storybook. Storybook is a faster way to see how your template will look (it's faster than to start your app, deploy, drag and drop or whatever)

Basically our template just provide what we think is essential to build your own
- typescript (to get correct types while you create your template)
- storybook (to see your template while you develop)
- tests
- integration tests
- and so on

If there is sth you dont need, dont use it, if you dont want to use typescript go ahead, if you dont wan tot use react, go ahead (for instace I made a try with svelte https://github.com/Open-Attestation/decentralized-renderer-svelte-template)

**Comment by laykoonjune** [comment]
Ok, noted with thanks.
