### ISSUE TITLE
Unable to load viewer in dev.opencerts.io

### ISSUE THREAD

**Issue by laykoonjune** [OpenCerts/demo-opencerts-renderer#370]
![image](https://user-images.githubusercontent.com/46921398/77025379-e3d6bc80-69cb-11ea-9986-a366a6f108bd.png)
I have deploy my latest code with the changes to tsx and i am able to run in story book however I am unable to view the certs in dev.opencerts.io 
It seems to be able to call the my document renderer but it is unable to load. 
Do you guys have any ideas? thanks in advance.

**Comment by Nebulis** [comment]
Please share a document to test

**Comment by laykoonjune** [comment]
[MCPDC_test.txt](https://github.com/OpenCerts/demo-opencerts-renderer/files/4352506/MCPDC_test.txt)
Please rename the file format back to .opencert before testing.

**Comment by Nebulis** [comment]
I dont see any error on my side but I dont see the certificate too. Do you have a link to the code ?

**Comment by laykoonjune** [comment]
https://github.com/laykoonjune/NYPOpenCerts

**Comment by Nebulis** [comment]
I think I know the problem but I would like to try something (sorry you will be my guinea pig :) ). Could you update `@govtechsg/decentralized-renderer-react-components` to v2.1.0, deploy again and retry ?

**Comment by laykoonjune** [comment]
Change and redeployed. 
![image](https://user-images.githubusercontent.com/46921398/77031251-f9ec7900-69db-11ea-9c2a-cfaa271ad02e.png)

**Comment by Nebulis** [comment]
Ok does the message help ?

**Comment by Nebulis** [comment]
I release `@govtechsg/decentralized-renderer-react-components@2.1.1` because the document displayed is window.document and not props.document :see_no_evil: 

The message is still the same, it should help you to understand the problem. Let me know.

**Comment by laykoonjune** [comment]
![image](https://user-images.githubusercontent.com/46921398/77039849-bd2b7c80-69f1-11ea-8ecd-52ec53f840ef.png)
update to the latest 2.1.1 however is not loading the certificate after i did some rectification to the document renderer.

**Comment by Nebulis** [comment]
Yes that was the first error, but I wanted to see if the message could help you for the configuration. (guinea pig :) )

You can get rid of the default property now:
https://github.com/laykoonjune/NYPOpenCerts/blob/master/src/templates/index.tsx#L5

For the error:
https://github.com/laykoonjune/NYPOpenCerts/blob/master/src/templates/NYPMCPDC/index.tsx#L1

You import the component using default export while the component is exported using named export. You can change the line to:
```typescript
import {CertificateTemplate} from "./certificate";
```

I recommend you to stick to named import, but just a personal recommendation feel free to use what you want

**Comment by laykoonjune** [comment]
Thanks so much for your assistance. Don't mind to be guinea pig as long as the things works.

**Comment by laykoonjune** [comment]
Just curious these setting won't be check in storybook hence it displayed without any error?

**Comment by Nebulis** [comment]
Exact, storybook is only to test your template. If you want to test the configuration, you can follow the guideline here => https://github.com/Open-Attestation/decentralized-renderer-react-template#testing-the-templates-in-an-integrated-environment
