### ISSUE TITLE
Template change not reflect in the viewer at https://www.opencerts.io/viewer

### ISSUE THREAD

**Issue by SP-INDT-OpenCert** [OpenCerts/demo-opencerts-renderer#371]
we make change to the template and commit it.
But the effect of the change in the template is not shown when viewing a certificate using this template

Details:
file changed: demo-opencerts-renderer/src/components/templates/SPTemplate/PET/SP-2019-DPCERT/certificate.js

**Comment by Nebulis** [comment]
where did you change ? (which repo)

**Comment by SP-INDT-OpenCert** [comment]
The actual change did not show, so this file has a minor change in line 51 the text is added with a coma:
having successfully completed the course of study, was awarded the

**Comment by SP-INDT-OpenCert** [comment]
in the repo: demo-opencerts-renderer
is that what you ask ?

**Comment by Nebulis** [comment]
I'm asking where did you make the commit ? I don't see an commits made by you in this repository

**Comment by SP-INDT-OpenCert** [comment]
https://github.com/SP-INDT-OpenCert/demo-opencerts-renderer.git is the repo
file changed: demo-opencerts-renderer/src/components/templates/SPTemplate/PET/SP-2019-DPCERT/certificate.js

**Comment by Nebulis** [comment]
It's a different repository. We don't deploy from external repository. Otherwise anyone could just come, and change the code at will.

IF you want your code to be added to this repository, you need to [open a pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) and wait for a review

**Comment by Nebulis** [comment]
OK you made a change into your repository and wonder why you cant see the change in Opencerts. Your repository probably didnt deploy automatically after your commit nd we have no control on your own repository

**Comment by SP-INDT-OpenCert** [comment]
Hi, Who can deploy the change?

**Comment by Nebulis** [comment]
The owner of the repo, so you

**Comment by SP-INDT-OpenCert** [comment]
how to do that? hope you can tell us

**Comment by Nebulis** [comment]
I unfortunately cant'. There are thousands way to deploy a website. I am not aware of the processes that you use.

**Comment by SP-INDT-OpenCert** [comment]
we have made changes before,  using GitHub desktop we commit the changes and then push  original.  And the change is show in the opencert viewer.  We didn't do a deploy.  Was the "auto deployment" taken down ?

**Comment by Nebulis** [comment]
Once again, I do not have any control on your process and can't tell you what's going on.

**Comment by SP-INDT-OpenCert** [comment]
Hi, we found the problem as logged in the Netlify deployment. 
Thanks

**Comment by Nebulis** [comment]
Great to hear :+1:
