### ISSUE TITLE
[for advice] To have an HTML page to preview OpenCerts document (similar to V1.5)

### ISSUE THREAD

**Issue by mmysgp** [OpenCerts/demo-opencerts-renderer#380]
Hi Team,

Previously there is a test html file in the legacy templates to preview the generated OpenCerts document before issuing it on blockchain.
[[legacy-templates](https://github.com/OpenCerts/legacy-templates)/[test](https://github.com/OpenCerts/legacy-templates/tree/master/test)/index.html]

It’s a very good feature which can be easily used in our ERP system to create a preview function.
We noticed that the legacy index.html does not work for V2 samples.
![ADE0DF5F-B841-459A-93C8-52E9F0B7997C](https://user-images.githubusercontent.com/36496605/163834618-bef8a26e-212d-4f1d-b908-c8a062660d5b.png)

May I know whether you can provide a similar html page calling OpenCerts V2 renderer to preview documents or provide the detailed implementation guide for it?

Thanks.

**Comment by mmysgp** [comment]
Hi,

may I know whether there is any update on this matter? 

Thanks

**Comment by simboonlong** [comment]
for decentralised renderers, you can also load respective document and simulate the renderer by first running `npm run dev`, then concurrently  `npm run example:application` as shown in [script](https://github.com/Open-Attestation/decentralized-renderer-react-template/blob/master/package.json#L22)

either storybook or the above way for previewing is fine

**Comment by mmysgp** [comment]
Hi @HJunyuan & @simboonlong :  for developers, storybook is good enough for development and preview. however, it will be difficult for us to use storybook in our ERP system.  

Let me elaborate the use case further:  
We have developed a preview function in the ERP system to allow users to click a button to preview the OpenCerts before issuing it on blockchain.  This preview function is very useful as users can do the final check for data/template and fish out mistakes before touching blockchain.  What we do is to dynamically generate a HTML page with OpenCerts data embedded in the file and point the URL of the iframe to the renderer.  When user opens the HTML page, the Javascript is running inside user's browser, hence, no dependency on the ERP system.  
e.g.
![image](https://user-images.githubusercontent.com/36496605/165275852-ef546a87-a649-461c-b316-cd115b697098.png)

If we can't have a similar HTML or ERP-independent solution,  we are going to break the existing preview function in the ERP system when we implement V2 renderer and this is the least wanted. That's why we requested for help to develop such HTML page for the V2 renderer based on either this project (demo-opencerts-renderer) or the decentralized-renderer-react-template project.  

Hope this clarifies and look forward to hearing from you soon.

Thanks.

**Comment by simboonlong** [comment]
here is an [example](https://github.com/Open-Attestation/decentralized-renderer-react-template/pull/14/files#diff-868e27043cd0a7955c1b7ee6f0e0fe302b6f370fa872799c967e7449eb2929b7R19). this example has a dummy bare minimal demo of a "cover letter" template.

concurrently run `npm run dev` and `npm run example:application`, then go to localhost:8080 to preview. note that the above sample will not be merge into the repo. reason being we encourage integrators to build their own oa template renderer, [react flavor](https://github.com/Open-Attestation/decentralized-renderer-react-template).

you can reference the html.

**Comment by simboonlong** [comment]
refer to this [example](https://github.com/Open-Attestation/decentralized-renderer-react-template/pull/17).
read the docs at [here](https://github.com/Open-Attestation/decentralized-renderer-react-components#actions-api).

**Comment by mmysgp** [comment]
@simboonlong : Thanks for your help! It works.

**Comment by mmysgp** [comment]
just a small issue.  it keeps appending tabs when clicking "Render OA Document".
I think we can handle that.
Thanks.

![image](https://user-images.githubusercontent.com/36496605/167075381-3a345931-cdc0-4a39-92b1-94419e041558.png)
