### ISSUE TITLE
npm run commands are not working

### ISSUE THREAD

**Issue by mmysgp** [OpenCerts/demo-opencerts-renderer#381]
Tried the following commands, but hit errors.
$ npm run test:watch # run tests with Jest
![image](https://user-images.githubusercontent.com/36496605/164730154-530e341a-d536-442c-896c-5696cf710401.png)

$ npm run build # build component
![image](https://user-images.githubusercontent.com/36496605/164730359-41d77e1e-c2e5-4076-86a2-16fb810f47f5.png)

Please also advise how to start the application.  There is no "npm run start" or "npm run dev" in the package.json

**Comment by HJunyuan** [comment]
For the first screenshot:
You may need to change the command inside `package.json` from `jest --ci --watch` to `jest --ci --watchAll`

For the second screenshot:
If you're running Windows, you might have to utilise [cross-env](https://www.npmjs.com/package/cross-env)

Perhaps you can try out this repo instead as well: https://github.com/Open-Attestation/decentralized-renderer-react-template

**Comment by mmysgp** [comment]
Managed to get it working based on the advice. 
Thanks.
