### ISSUE TITLE
Proposal - Turn API into redux style action

### ISSUE THREAD

**Issue by Nebulis** [OpenCerts/demo-opencerts-renderer#50]
Currently every actions handled by the decentralized renderer needs to be bound. The goal of this proposal is to turn the API into a single function which will use redux style actions for both ways communication.
```jsx harmony
const childFrameConnection = connectToChild({
  iframe,
  methods: {
    broadcast // (?)
  }
}).promise;
const parentFrameConnection = connectToParent({
  methods: {
    emit // (?)
  }
}).promise;
```

where each functions would take two parameters
1. `type`: string representing type of the event (for instance `SET_HEIGHT`)
1. `payload`: the payload can be anything and represent any data to be given to handlers, from simple types (number, string, etc.), to complex types (arrays, objects, etc.)

Every handled actions can be exposed so that consumer can directly now what's possible to do.

#### Benefits
API will be stable (no changes needed), adding or removing actions would not break compatibility

#### Drawbacks
TBD

#### Note
emit/broadcast are terms used by angular v1 for parent/child communication (see. http://bipinjoshi.net/articles/5d8be0b6-e294-457e-82b0-ba7cc10cae0e.aspx). I may be wrong in the example on which one should use the correct function.

**Comment by yehjxraymond** [comment]
This means binding ALL communications between the parent and child to redux style actions?

**Comment by Nebulis** [comment]
yeah exactly, only one function to declare on parent and child, then follow redux style.

Note that it's actions following this pattern https://github.com/piotrwitek/typesafe-actions#1-basic-actions
