### ISSUE TITLE
Proposal - Uses template id instead of tab index for tab selection

### ISSUE THREAD

**Issue by Nebulis** [OpenCerts/demo-opencerts-renderer#51]
Template is an array of object:
```js
[
  {
    id: "certificate",
    label: "Certificate",
    template: DemoCert
  },
  {
    id: "transcript",
    label: "Transcript",
    template: DemoTranscript
  },
  {
    id: "media",
    label: "Media",
    template: DemoMedia
  }
];
```
Currently the position of the template in the array is used to select the template to render. This proposal suggest to use the id exposed from objects.

#### Benefits
The way consumer handles template doesn't matter (order can be changed, templates can be hidden)

#### Drawbacks
TBD

**Comment by yehjxraymond** [comment]
Do you intend to change the structure of the data or change the way its being passed around in the application. I can agree that using ID to select template will be more straightforward. 

One problem I'm thinking of is that using ID to identify, how would we define which is the default template to show. Right now we default to the first template in the array.

**Comment by Nebulis** [comment]
```
Do you intend to change the structure of the data or change the way its being passed around in the application. I can agree that using ID to select template will be more straightforward.
```
No changes in data structure, just change the way it's being passed around. Currently we do `child.selectTemplateTab(i);` where i is an integer for the position of the selected template in the array. With that proposal we would change `i` to the index name (a string) 

```
One problem I'm thinking of is that using ID to identify, how would we define which is the default template to show. Right now we default to the first template in the array.
```
Not sure to understand the problem. Currently there is also no way as we default to the first template in the array list. Am I missing something?
